### ISSUE TITLE
How to display all the charts as coverflow with  fusioncharts Jquery?

### ISSUE THREAD

**Issue by inothings** [fusioncharts/jquery-fusioncharts#3]
I am using fusioncharts-jquery to display my chart, and now I want to display all my charts as coverflow, is there any way?

Thanks!

**Comment by rohitkr** [comment]
Hello,
Yes, you can render FusionCharts as coverflow using fusioncharts.jqueryplugin.
1. Replace coverflow `<img>` element with `<div>` (container to render FusionCharts).
2. Define unique ID for each container elements.
3. On document ready use the insertFusionCharts method to render the chart.

I have also attached a sample for your reference.
[coverflow.zip](https://github.com/fusioncharts/fusioncharts-jquery-plugin/files/106373/coverflow.zip)

**Comment by inothings** [comment]
Thanks Rohit! It looks very neat!

Joyce
