### ISSUE TITLE
Error when using it with angular 2 

### ISSUE THREAD

**Issue by agustincelentano** [fusioncharts/jquery-fusioncharts#7]
Hi,

I am trying to use it following the instructions on the page. 

The problem is that I have this error: 

fusioncharts/fusioncharts.charts"' resolves to a non-module entity and cannot be imported using this construct.

With this line: import * as Charts from 'fusioncharts/fusioncharts.charts';

using this configuration in my tsconfig.json. I read something releate of how things should be imported depending on what ES version are you using but i did not find any solution: 

{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib" : ["es2015", "dom"]

  },

Any ideas?

**Comment by ashok1994** [comment]
You can  use angular wrapper (Angular 2 and above ) for fusioncharts 
https://github.com/fusioncharts/angular-fusioncharts

**Comment by ashok1994** [comment]
Closing for now , please reopen if the problem persists
